# DOES NOT HAVE ANY INDEXS
# SPREAD ALL OVER THE PLACE IN MEMORY, NOT ATTACHED TOGETHER
# HEAD AND TAIL ARE THE FIRST AND LAST NODES
# TAIL NODE POINT TO NONE
# O(N) -> TO ACCESS ELEMENTS
# O(1) -> TO ADD AN ELEMENT
# O(N) -> TO REMOVE THE END NODE
# O(1) -> ADD ELEMENT FROM FRONT
# O(1) -> REMOVE ELEMENT FROM FRONT
# O(N) -> ADD IN THE MIDDLE 
# O(N) -> REMOVE IN THE MIDDLE
